### ISSUE TITLE
Support history

### ISSUE THREAD

**Issue by LennyPenny** [Moder112/MassAnnotationDownloader#2]
Would be awesome if this somehow could support https://www.youtube.com/feed/history, so one can save all the videos one has watched

**Comment by Moder112** [comment]
I do not believe this would be possible even with the use of the youtube api, I tried to look into this, but not even google takeout allows you to export your entire history, it doesn't seem like youtube actually saves it for very long before getting rid of it, my personal history goes only as far as March 28th 2018

**Comment by Moder112** [comment]
You can download all of the channels that you are subscribed to, through a slightly hack-y solution.
Basically, you go to this page:
https://takeout.google.com/settings/takeout
On the page with all of the google service, you click on "Select none", then manually check youtube.
Click on the arrow to get advanced settings and uncheck all of the data types besides subscribtions, then change the subscriptions format to json.
After you've done all that, you wait for google to collect your data and once you get the confirmation email, you can unzip the takeout, drop the program attatched into the same folder as the subscribtions.json file and run it. 
It should generate a text file with all of the channels which then you can feed into the main program.
[subtotxt.zip](https://github.com/Moder112/MassAnnotationDownloader/files/2754450/subtotxt.zip)

**Comment by LennyPenny** [comment]
That's a good alternative solution 
Thanks a lot!

**Comment by Moder112** [comment]
Hey so, It's a shame you saw this so late, because youtube deprecated their annotation api yesterday, the program is unable to retrieve any annotation info anymore, I'm sorry about this.
